
server:
  port: 8080
  servlet:
    context-path: /api
  url:
    prefix: /api
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite::resource:db/database
    driver-class-name: org.sqlite.JDBC
    hikari:
      auto-commit: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #flyway 配置，自动数据库升级
  flyway:
    clean-disabled: false
    baselineOnMigrate: true

security:
  # 默认为 authorization ，d2-admin示例中为X-Token
  tokenHeader: "authorization"
  # 默认为 "Bearer " ，d2-admin示例中无prefix
  tokenPrefix: ""
  # 这里设置jwt的密钥
  jwtSecret: yourSecret
  jwtIssuer: greper
  #token有效期一天
  tokenExpiration: 86400

logging:
  level:
    com.veryreader: DEBUG
    com.ibatis: DEBUG
    com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
